### PR TITLE
feat: sync pregnancy value sets with IG

### PR DESCRIPTION
**Pull request by whichwit**
IG updated with changes to `NA` pregnancy status code display value to "not applicable".

### CODE REVIEW

**Comment by whichwit** [comment]
Can we merge this ahead of official IG update?

**Comment by johnarleyburns** [comment]
I would wait for MITRE’s input first.

**Comment by whichwit** [comment]
Link to updated commit to the IG repo: https://github.com/HL7/vrdr/commit/ae53306c284ea749b44477180382d45a6a13a5ea

**Comment by whichwit** [comment]
IG is updated with the correction.

**Review by johnarleyburns — APPROVED** [review]

**Pull request merged**
